title: Ajinkya Pathak # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b><p>ğŸ Pythonist ğŸ¤– AI enthusiastğŸ“Š </b></p>
  <br>
  <i>Being enthusiastic learner, interested in exploring new tech skills in Artificial Intelligence, working as a Software Engineer with PG      Diploma in Big Data Analytics with â€˜Aâ€™ grade from CDAC and almost 2 years of experience using Python, computer vision, machine            learning, natural language process, end-to-end deployment.</i>
  <br><br>
  <a href="https://www.linkedin.com/in/ajinkyanpathak/"><img src="https://img.shields.io/badge/-Linkedin%20profile-blue"/></a> 
  <br>
  <a href="https://www.youracclaim.com/users/ajinkyanpathak/badges"><img src="https://img.shields.io/badge/-Acclaim%20badges-orange"/></a> 
  <br>
  <a href="https://public.tableau.com/profile/ajinkyapathak#!/"><img src="https://img.shields.io/badge/-Tableau%20profile-yellowgreen"/></a> 
  <br>
  <a href="https://www.slideshare.net/slideshow/embed_code/key/sdbFJ7pdh0Wx9O"><img src="https://img.shields.io/badge/-Slideshare-green"/></a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
