title:  Ajinkya N. Pathak # your name (or website title) here
logo: "/images/circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <marquee><b>Software Engineer ğŸ‘¨â€ğŸ’»|Pythonist ğŸ|AI ğŸ¤–|Data science ğŸ“ˆ|Machine Learning âš™ï¸|Data Visualization ğŸ“Š </b></marquee>
  <br><br>
  <a href="https://www.linkedin.com/in/ajinkyanpathak/" target="_blank"><img src="https://img.shields.io/badge/-Linkedin%20profile-blue"/></a> 
  <br>
  <a href="https://www.youracclaim.com/users/ajinkyanpathak/badges" target="_blank"><img src="https://img.shields.io/badge/-Acclaim%20badges-orange"/></a> 
  <br>
  <a href="https://public.tableau.com/profile/ajinkyapathak#!/" target="_blank"><img src="https://img.shields.io/badge/-Tableau%20profile-yellowgreen"/></a> 
  <br>
  <a href="https://www.slideshare.net/slideshow/embed_code/key/sdbFJ7pdh0Wx9O" target="_blank"><img src="https://img.shields.io/badge/-Slideshare-green"/></a>
  <br>
  <a href="https://drive.google.com/file/d/1hMC4oBnY2MH0Ymq15b3pHhi2CNSDtqMJg8iFiTPIvCQ" target="_blank"><img src="https://img.shields.io/badge/View-Resume-blueviolet"/></a>
  <br>
  <a href="https://drive.google.com/file/d/1sXr3C_mrQ11WoJe9ngQAKIrYEUetT2AR" target="_blank"><img src="https://img.shields.io/badge/View-Psychometric%20results-red"/></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-178738326-1 # your Google Analytics tracking ID here
